# Use the official MySQL image as a base
FROM mysql:8

# Environment variables
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_DATABASE=cloud_project
ENV MYSQL_USER=flask_user
ENV MYSQL_PASSWORD=password

# Copy SQL script to initialize the database
COPY init.sql /docker-entrypoint-initdb.d/
