version: '3.8'

services:
  flask:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: cloud_project
      MYSQL_USER: flask_user
      MYSQL_PASSWORD: password
